spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/conference
    username: admin
    password: admin
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 9192